version: '3'

volumes:
  postgres_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./keys/tls.crt:/etc/nginx/ssl/tls.crt
      - ./keys/tls.key:/etc/nginx/ssl/tls.key
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
    env_file:
      - .env
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev
    ports:
      - 8443:8443
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KC_HTTPS_PROTOCOLS: TLSv1.3,TLSv1.2
      KC_HTTPS_KEY_STORE_FILE: /etc/x509/https/keystore.jks
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
    env_file:
      - .env
    volumes:
      - ./keys/keystore.jks:/etc/x509/https/keystore.jks
    depends_on:
      - postgres
